version: '3'
services:
  postgres:
    image: postgres:10
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_DB=speeches
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_PORT=5432